# Generated by Django 6.0.5 on 2026-05-06 16:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='ФИО должно содержать только символы кириллицы и пробелы', regex='^[а-яА-ЯёЁ\\s]+$')], verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='ФИО должно содержать только символы кириллицы и пробелы', regex='^[а-яА-ЯёЁ\\s]+$')], verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='ФИО должно содержать только символы кириллицы и пробелы', regex='^[а-яА-ЯёЁ\\s]+$')], verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +7(XXX)-XXX-XX-XX', regex='^\\+7\\(\\d{3}\\)-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('oms_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Полис ОМС должен содержать 16 цифр', regex='^\\d{16}$')], verbose_name='Полис ОМС')),
                ('snils', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='СНИЛС должен быть в формате XXX-XXX-XXX XX', regex='^\\d{3}-\\d{3}-\\d{3} \\d{2}$')], verbose_name='СНИЛС')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100, verbose_name='Специальность')),
                ('cabinet', models.CharField(blank=True, max_length=20, verbose_name='Кабинет')),
                ('work_schedule', models.TextField(blank=True, verbose_name='График работы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата приема')),
                ('start_time', models.TimeField(verbose_name='Начало приема')),
                ('end_time', models.TimeField(verbose_name='Конец приема')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для записи')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='registry.doctor', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Запись в расписании',
                'verbose_name_plural': 'Расписание врачей',
                'ordering': ['date', 'start_time'],
                'unique_together': {('doctor', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Дата приема')),
                ('appointment_time', models.TimeField(verbose_name='Время приема')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('completed', 'Завершен'), ('cancelled', 'Отменён'), ('no_show', 'Не явился')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('complaint', models.TextField(blank=True, verbose_name='Жалобы')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Диагноз')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки врача')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='registry.doctor', verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='registry.patient', verbose_name='Пациент')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='registry.schedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
